name: .NET

on:
  push:
    branches: [ netstandard-eddsa ]
  pull_request:
    branches: [ netstandard-eddsa ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build crypto
      run: dotnet build crypto\src --no-restore --configuration Release
#    - name: Build tests
#      run: dotnet build crypto\test --no-restore --configuration Release
#    - name: Test
#      run: dotnet test crypto\test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --configuration Release
#    - name: Publish test results
#      uses: dorny/test-reporter@v1
#      if: success() || failure()
#      with:
#        name: "test results"
#        path: "**/TestResults/*.trx"
#        reporter: dotnet-trx
    - name: Pack
      run: dotnet pack crypto/src --configuration Release
    - name: Publish
      env:
        token1: ${{ secrets.NUGET_TOKEN }}
        token2: "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"
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/emclient/index.json -n github
        echo API key $token1 $token2
        dotnet nuget push crypto/src/bin/Release/MailClient.BouncyCastle.1.8.10.54.nupkg -s github -k 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
