name: Build and publish

on:
  push:
    branches: [ netstandard-eddsa ]
  pull_request:
    branches: [ netstandard-eddsa ]

#permissions:
#  packages: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
#    - name: Build crypto
#      run: dotnet build crypto/src --no-restore --configuration Release
#    - name: Build tests
#      run: dotnet build crypto/test --no-restore
#    - name: Run tests
#      run: dotnet test crypto/test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Build
      run: dotnet build --no-restore

  tests:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: "test results"
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx

  publish:
    permissions:
      packages: write

    needs: tests
    runs-on: windows-latest
    steps:
    - name: Pack
      run: dotnet pack crypto/src --configuration Release
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/emclient/index.json -n github
        dotnet nuget push crypto/src/bin/Release/MailClient.BouncyCastle.${{ env.GitBuildVersion }}.nupkg -s github --api-key ${{ secrets.GITHUB_TOKEN }}
